

string = 'CACAGGCTCACAGGCCCATAGCACAGGCAGCCCACAGGCACACAGGCGTGGTCAACCACAGGCCTACCACAGGCCACAGGCCACAGGCCCCACAGGCACACAGGCTAGTTCACAGGCCCTGACAGCACAGGCGACTGCACAGGCTCTTAACCGCACACAGGCCACAGGCTCGGGGACACAGGCACACAGGCCACAGGCCCACAGGCGGCTACCACAGGCGTCACAGGCTCACAGGCCACAGGCTAACACAGGCGCCACACAGGCCACAGGCCTACCACAGGCGGCACAGGCGAGAGCCACAGGCGTTCTCACAGGCGCACACAGGCTCAATGAGTCCACAGGCGGGACACAGGCTCACAGGCATTGCACAGGCCACAGGCTCACAGGCCACAGGCCCACAGGCAGCACAGGCGCCATGGCTACACAGGCTCACACAGGCCTCCACCCGTCCACAGGCAACCAATGGCACAGGCTCACAGGCTCCACAGGCGCACAGGCACACAGGCCCAGGACCACAGGCCGACACAGGCCACAGGCCTAATTATCACAGGCGAGAACCACAGGCCACAGGCGTACACAGGCCACAGGCTTCACAGGCTCACAGGCTGTCACAGGCTCCACAGGCGTAGCACAGGCTACACAGGCCGGCATGACACAGGCCCACAGGCACTAGACACAGGCGTCACAGGCCACAGGCCACGTGCACAGGCCACAGGCAAGATACACAGGCGCCACAAACGATAGGCTTCCACAGGCCACAGGCGCGTTCTCACAGGCCACAGGCGGCACAGGCGCACAGGCCACAGGCTCACAGGCTTCACACAGGCCACAGGCCACAGGCCACAGGCCACAGGCGCGTCACAGGCATACGCACAGGCCACAGGCCTCACGCACAGGCCCCACAGGCTGCTGACACAGGCCACAGGCCACAGGCCACAGGCTTTCTTACCTCACAGGCCCACAGGCGACACAGGCC'
sub_string  ='CACAGGCCA'



output=""

lista = []
sub_lista = []

sub_lista = list(sub_string)
lista = list(string)

tam_sub_lista = len(sub_lista)

for i in range(0,len(lista)):
    if sub_lista == lista[i:i+tam_sub_lista]:
        print(type(lista))
        print(type(sub_lista))
        output += str(i+1) + " "
        
print(output)
